RubyApp/DentlistApp/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index', as: "home"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #Logind de user y dentist
  get 'api/loginp', to: "welcome#loginp"
  get 'api/logind', to: "welcome#logind"
  

  #1 GET Sin autentificacion
  get 'api/posts', to: "welcome#posts"


  #2 get all
  get 'api/allpains', to: "welcome#allpains"
  get 'api/allpainsp', to: "welcome#allpainsp"

  #2 get by id
  get 'api/patientbyid', to: "welcome#patientById"
  get 'api/dentistbyid', to: "welcome#dentistById"

  #3 post
  get 'api/postPain', to: "welcome#postPain"
  get 'api/postDate', to: "welcome#postDate"
  get 'api/postMessage', to: "welcome#postMessage"

  #3delete
  get 'api/delPatient', to: "welcome#delPatient"
  get 'api/delDentist', to: "welcome#delDentist"
  get 'api/delPain', to: "welcome#delPain"


  #3patch

  get 'api/updateDate', to: "welcome#updateDate"
  get 'api/updatePatient', to: "welcome#updatePatient"
  get 'api/updateDentist', to: "welcome#updateDentist"




  get 'api/resultado', to: "welcome#resultado"  
end

RubyApp/DentlistApp/app/controllers/welcome_controller.rb
require 'httparty'
require 'json'


class WelcomeController < ApplicationController
  include HTTParty
#LOGIN PACIENTE
  @token = 'thisisatoken' 
  def loginp
      @url = MYHOST + "/api/auth/loginPatient"

      @email = params[:email]
      @password = params[:password]
      puts @url
      @respuesta = HTTParty.post(
      @url.to_str,
      body: {
        "email": @email,
        "password": @password
      }
        )

      @body = @respuesta.body

      @parsed = JSON.parse(@body)
      @token = @parsed["patientToken"]
      puts '################################################################3'
      puts @token
      puts '################################################################3'
      if @body 
        redirect_to api_resultado_path(:body => @body, :token => @token)
        return
      end
  end
#LOGIN DENTISTA
  def logind
    @url = MYHOST + "/api/auth/loginDentist"

    @email = params[:email]
    @password = params[:password]

    @respuesta = HTTParty.post(
    @url.to_str,
    body: {
      "email": @email,
      "password": @password
    }
      )

    @body = @respuesta.body
    if @body 
      redirect_to api_resultado_path(:body => @body, :token => @token)
      return
    end
  end
############
# 1 Get SIN AUTENTIFICAR
  def posts
    @url = MYHOST + "/api/posts/all"


    @respuesta = HTTParty.get(
    @url.to_str
      )

    @body = @respuesta.body
    if @body 
      redirect_to api_resultado_path(:body => @body, :token => @token)
      return
    end
  end

###################
#CON AUTENTIFICAR

#GET BY ID
  def patientById
    @url = MYHOST + "/api/patient/data"

    @token = params[:token]

    @auth = "Bearer " + @token
    @respuesta = HTTParty.get(
    @url.to_str,
    headers: {
      "Authorization": @auth
    }
      )

    @body = @respuesta.body
    if @body 
      redirect_to api_resultado_path(:body => @body, :token => @token)
      return
    end
  end
  def dentistById
    @url = MYHOST + "/api/dentist/data"
    #Recibo parametros

    @token = params[:token]

    @auth = "Bearer " + @token
    @respuesta = HTTParty.get(
    @url.to_str,
    headers: {
      "Authorization": @auth
    }
      )

    @body = @respuesta.body
    if @body 
      redirect_to api_resultado_path(:body => @body, :token => @token)
      return
    end
  end
############################################

#2 Get All
  def allpains
    @url = MYHOST + "/api/pain/all"
    #Recibo parametros

    @token = params[:token]

    @auth = "Bearer " + @token
    @respuesta = HTTParty.get(
    @url.to_str,
    headers: {
      "Authorization": @auth
    }
      )

    @body = @respuesta.body
    if @body 
      redirect_to api_resultado_path(:body => @body, :token => @token)
      return
    end
  end

  def allpainsp
    @url = MYHOST + "/api/allpains/pains"
    #Recibo parametros

    @token = params[:token]

    @auth = "Bearer " + @token
    @respuesta = HTTParty.get(
    @url.to_str,
    headers: {
      "Authorization": @auth
    }
      )

    @body = @respuesta.body
    if @body 
      redirect_to api_resultado_path(:body => @body, :token => @token)
      return
    end
  end
######################################################
# 3 Post
  def postPain
    @url = MYHOST + "/api/pain/new"
    #Recibo parametros

    @token = params[:token]
    @name =params[:name]
    @description =params[:description]
    @category =params[:category]

    @auth = "Bearer " + @token
    @respuesta = HTTParty.post(
    @url.to_str,
    headers: {
      "Authorization": @auth
    },
    body: {
      "name": @name,
      "description": @description,
      "category": @category
    }
      )
    @body = @respuesta.body
    if @body 
      redirect_to api_resultado_path(:body => @body, :token => @token)
      return
    end
  end

  def postDate
    @url = MYHOST + "/api/date/new"
    @token = params[:token]
    @painId =params[:painId]
    @schedule =params[:schedule]
    @price =params[:price]
    @message=params[:message]

    @auth = "Bearer " + @token
    @respuesta = HTTParty.post(
    @url.to_str,
    headers: {
      "Authorization": @auth
    },
    body: {
        "painId": @painId,
        "schedule": @schedule,
        "price": @price,
        "message": @message
    }
      )
    @body = @respuesta.body
    if @body 
      redirect_to api_resultado_path(:body => @body, :token => @token)
      return
    end
  end

  def postMessage
    @url = MYHOST + "/api/message/new"
    @token = params[:token]
    @chatId =params[:chatId]
    @idReceive =params[:idReceive]
    @body =params[:body]

    @auth = "Bearer " + @token
    @respuesta = HTTParty.post(
    @url.to_str,
    headers: {
      "Authorization": @auth
    },
    body: {
        "chatId": @chatId,
        "idReceive": @idReceive,
        "body": @body
    }
      )
    @body = @respuesta.body
    if @body 
      redirect_to api_resultado_path(:body => @body, :token => @token)
      return
    end
  end
## 3 DELETE
  def delPatient
    @url = MYHOST + "/api/deletepatient/Delete"
    @token = params[:token]
    
    @auth = "Bearer " + @token
    @respuesta = HTTParty.delete(
    @url.to_str,
    headers: {
      "Authorization": @auth
    }
      )
    @body = @respuesta.body
    if @body 
      redirect_to api_resultado_path(:body => @body, :token => @token)
      return
    end
  end

  def delDentist
    @url = MYHOST + "/api/deletedentist/Delete"
    @token = params[:token]
    
    @auth = "Bearer " + @token
    @respuesta = HTTParty.delete(
    @url.to_str,
    headers: {
      "Authorization": @auth
    }
      )
    @body = @respuesta.body
    if @body 
      redirect_to api_resultado_path(:body => @body, :token => @token)
      return
    end
  end

  def delPain
    
    @token = params[:token]
    @idpain = params[:idpain]
    @url = MYHOST + "/api/deletepain/delete/"+ @idpain
    
    @auth = "Bearer " + @token
    @respuesta = HTTParty.delete(
    @url.to_str,
    headers: {
      "Authorization": @auth
    }
      )
    @body = @respuesta.body
    if @body 
      redirect_to api_resultado_path(:body => @body, :token => @token)
      return
    end
  end

## 3 UPDATE

  def updateDate
    @url = MYHOST + "/api/dentist/updateDateApi"
    @token = params[:token]
    @dateId = params[:dateId]
    @state = params[:state]
  
    
    @auth = "Bearer " + @token
    @respuesta = HTTParty.patch(
    @url.to_str,
    headers: {
      "Authorization": @auth
    },
      body: {
        "dateId": @dateId,
        "state": @state 
    }
      )
    @body = @respuesta.body
    if @body 
      redirect_to api_resultado_path(:body => @body, :token => @token)
      return
    end
  end

  def updatePatient
    @url = MYHOST + "/api/patient/data/update"
    @token = params[:token]

    @name = params[:name]
    @age = params[:age]
    @phone = params[:phone]
    @address = params[:address]
    @city = params[:city]
    @email = params[:email]
    @rut = params[:rut]
    @isapre = params[:isapre]
    @password = params[:password]
   
    
    @auth = "Bearer " + @token
    @respuesta = HTTParty.patch(
    @url.to_str,
    headers: {
      "Authorization": @auth
    },
      body:   {
        "name": @name,
        "age": @age,
        "phone": @phone,
        "address": @address,
        "city": @city,
        "email": @email,
        "rut": @rut,
        "isapre": @isapre,
        "password": @password
      }
      )
    @body = @respuesta.body
    if @body 
      redirect_to api_resultado_path(:body => @body, :token => @token)
      return
    end
  end  

  def updateDentist
    @url = MYHOST + "/api/dentist/data/update"
    @token = params[:token]

    @name = params[:name]
    @year = params[:year]
    @phone = params[:phone]
    @address = params[:address]
    @city = params[:city]
    @email = params[:email]
    @rut = params[:rut]
    @voluntario = params[:voluntario]
    @speciality = params[:speciality]
    @university = params[:university]
    @password = params[:password]
   
    
    @auth = "Bearer " + @token
    @respuesta = HTTParty.patch(
    @url.to_str,
    headers: {
      "Authorization": @auth
    },
      body:   {
        "name": @name,
        "year": @year,
        "phone": @phone,
        "address": @address,
        "city": @city,
        "email": @email,
        "rut": @rut,
        "voluntario": @voluntario,
        "speciality": @speciality,
        "university": @university,
        "password": @password
      }
      )
    @body = @respuesta.body
    if @body 
      redirect_to api_resultado_path(:body => @body, :token => @token)
      return
    end
  end 

  def resultado
    @body = params[:body]
  end

end

RubyApp/DentlistApp/app/helpers/welcome_helper.rb
module WelcomeHelper
end

RubyApp/DentlistApp/app/views/welcome/index.html.erb
<header>
    <h1>DentList</h1>
    <p> Esta app consume la API DentList</p>
</header>

<div class="topnav">
    <a href="#">Atras</a>
   
    <a href="#" id="r">Inicio</a>
</div>

<div class="card">
    <h2>Acciones de la API </h2>
    <h5> Al hacer login recibes un token ya sea de dentista o paciente, algunas rutas requiren un token especifico para funcionar. </h5>
</div>

<div class="card">
<h1> Login</h1>
<br>
    <div class="card2">
        <h2> Login de usuario</h2>
        
        <%= form_with(url: api_loginp_path, method: "get", remote: false, local:true) do %>
            <div class="field" >
                <%= label_tag(:email, "email:") %>
                <%= text_field_tag(:email) %>
            </div>
            <div class="field" >
                <%= label_tag(:password, "password:") %>
                <%= text_field_tag(:password) %>
            </div>
            <div class="action" >
                <%= submit_tag("Login") %>
            </div>
        <% end %> 
    </div>

    <div class="card2">
        <h2> Login de dentista </h2>
        
        <%= form_with(url: api_logind_path, method: "get", remote: false, local:true) do %>
            <div class="field" >
                <%= label_tag(:email, "email:") %>
                <%= text_field_tag(:email) %>
            </div>
            <div class="field" >
                <%= label_tag(:password, "password:") %>
                <%= text_field_tag(:password) %>
            </div>
            <div class="action" >
                <%= submit_tag("Login") %>
            </div>
        <% end %>
    </div>
</div>
<div class="card">
    <h1> Ruta libre </h1>
    <br>
    <div class="card2">
        <h2> Get Posts (libre)</h2>
        
        <%= form_with(url: api_posts_path, method: "get", remote: false, local:true) do %>
    
            <div class="action" >
                <%= submit_tag("Get posts") %>
            </div>
        <% end %>
    </div>
</div>

<div class="card">
    <h1> Mensajes Paciente y Dentista </h1>
    <br>
    <div class="card2">
    <h2> Post Crear mensaje (paciente o dentista) </h2>

    <%= form_with(url: api_postMessage_path, method: "get", remote: false, local:true) do %>
        <div class="field" >
            <%= label_tag(:token, "token:") %>
            <%= text_field_tag(:token) %>
        </div>
        <div class="field" >
            <%= label_tag(:chatId, "chatId:") %>
            <%= text_field_tag(:chatId) %>
        </div>
        <div class="field" >
            <%= label_tag(:idReceive, "idReceive:") %>
            <%= text_field_tag(:idReceive) %>
        </div>
        <div class="field" >
            <%= label_tag(:body, "body:") %>
            <%= text_field_tag(:body) %>
        </div>
        <div class="action" >
            <%= submit_tag("Crear mensaje") %>
        </div>
    <% end %>
    </div>
</div>







<div class="card">
<h1> Rutas de Paciente </h1>
<br>
    <div class="card2">
        <h2> Get patient by id (paciente)</h2>
        
        <%= form_with(url: api_patientbyid_path, method: "get", remote: false, local:true) do %>

            <div class="field" >
                <%= label_tag(:token, "token:") %>
                <%= text_field_tag(:token) %>
            </div>
            <div class="action" >
                <%= submit_tag("Get patient") %>
            </div>
        <% end %>
    </div>
    <div class="card2">
        <h2> Get All pains Paciente (paciente) </h2>
        
        <%= form_with(url: api_allpainsp_path, method: "get", remote: false, local:true) do %>

            <div class="field" >
                <%= label_tag(:token, "token:") %>
                <%= text_field_tag(:token) %>
            </div>
            <div class="action" >
                <%= submit_tag("Get pains") %>
            </div>
        <% end %>
    </div>

    <div class="card2">
        <h2> Post Crear dolor (paciente) </h2>
        
        <%= form_with(url: api_postPain_path, method: "get", remote: false, local:true) do %>
            <div class="field" >
                <%= label_tag(:token, "token:") %>
                <%= text_field_tag(:token) %>
            </div>
            <div class="field" >
                <%= label_tag(:name, "name:") %>
                <%= text_field_tag(:name) %>
            </div>
            <div class="field" >
                <%= label_tag(:description, "description:") %>
                <%= text_field_tag(:description) %>
            </div>
            <div class="field" >
                <%= label_tag(:category, "category:") %>
                <%= text_field_tag(:category) %>
            </div>
            <div class="action" >
                <%= submit_tag("Crear dolor") %>
            </div>
        <% end %>
    </div>
    
    <div class="card2">
        <h2> DELETE Paciente (paciente) </h2>
        
        <%= form_with(url: api_delPatient_path, method: "get", remote: false, local:true) do %>
            <div class="field" >
                <%= label_tag(:token, "token:") %>
                <%= text_field_tag(:token) %>
            </div>
            <div class="action" >
                <%= submit_tag("Borrar paciente") %>
            </div>
        <% end %>
    </div>    
    <div class="card2">
        <h2> DELETE Pain (paciente) </h2>
        
        <%= form_with(url: api_delPain_path, method: "get", remote: false, local:true) do %>
            <div class="field" >
                <%= label_tag(:token, "token:") %>
                <%= text_field_tag(:token) %>
            </div>
            <div class="field" >
                <%= label_tag(:idpain, "idpain:") %>
                <%= text_field_tag(:idpain) %>
            </div>
            <div class="action" >
                <%= submit_tag("Borrar dolor") %>
            </div>
        <% end %>
    </div>
</div>
<div class="card2">
<h2> UPDATE Patient (paciente) </h2>

<%= form_with(url: api_updatePatient_path, method: "get", remote: false, local:true) do %>
    <div class="field" >
        <%= label_tag(:token, "token:") %>
        <%= text_field_tag(:token) %>
    </div>
    <div class="field" >
        <%= label_tag(:name, "name:") %>
        <%= text_field_tag(:name) %>
    </div>
    <div class="field" >
        <%= label_tag(:age, "age:") %>
        <%= text_field_tag(:age) %>
    </div>
    <div class="field" >
        <%= label_tag(:phone, "phone:") %>
        <%= text_field_tag(:phone) %>
    </div>
    <div class="field" >
        <%= label_tag(:address, "address:") %>
        <%= text_field_tag(:address) %>
    </div>
    <div class="field" >
        <%= label_tag(:city, "city:") %>
        <%= text_field_tag(:city) %>
    </div>
    <div class="field" >
        <%= label_tag(:email, "email:") %>
        <%= text_field_tag(:email) %>
    </div>
    <div class="field" >
        <%= label_tag(:rut, "rut:") %>
        <%= text_field_tag(:rut) %>
    </div>
    <div class="field" >
        <%= label_tag(:isapre, "isapre:") %>
        <%= text_field_tag(:isapre) %>
    </div>   
    <div class="field" >
        <%= label_tag(:password, "password:") %>
        <%= text_field_tag(:password) %>
    </div>                       
    <div class="action" >
        <%= submit_tag("Actualizar paciente") %>
    </div>
<% end %>
</div>
<div class="card">
<h1> Rutas de Dentista </h1>
<br>
    <div class="card2">
        <h2> Get dentist by id (dentista)</h2>
        
        <%= form_with(url: api_dentistbyid_path, method: "get", remote: false, local:true) do %>

            <div class="field" >
                <%= label_tag(:token, "token:") %>
                <%= text_field_tag(:token) %>
            </div>
            <div class="action" >
                <%= submit_tag("Get dentist") %>
            </div>
        <% end %>
    </div>
    
    <div class="card2">
        <h2> Get All pains Dentista (dentista)</h2>
        
        <%= form_with(url: api_allpains_path, method: "get", remote: false, local:true) do %>

            <div class="field" >
                <%= label_tag(:token, "token:") %>
                <%= text_field_tag(:token) %>
            </div>
            <div class="action" >
                <%= submit_tag("Get pains") %>
            </div>
        <% end %>
    </div>


    <div class="card2">
        <h2> Post Crear cita (dentista) </h2>
        
        <%= form_with(url: api_postDate_path, method: "get", remote: false, local:true) do %>
            <div class="field" >
                <%= label_tag(:token, "token:") %>
                <%= text_field_tag(:token) %>
            </div>
            <div class="field" >
                <%= label_tag(:painId, "painId:") %>
                <%= text_field_tag(:painId) %>
            </div>
            <div class="field" >
                <%= label_tag(:schedule, "schedule:") %>
                <%= text_field_tag(:schedule) %>
            </div>
            <div class="field" >
                <%= label_tag(:price, "price:") %>
                <%= text_field_tag(:price) %>
             </div>
            <div class="field" >
                <%= label_tag(:message, "message:") %>
                <%= text_field_tag(:message) %>
            </div>
            <div class="action" >
                <%= submit_tag("Crear cita") %>
            </div>
        <% end %>
    </div>





    <div class="card2">
        <h2> DELETE Dentista (dentista) </h2>
        
        <%= form_with(url: api_delDentist_path, method: "get", remote: false, local:true) do %>
            <div class="field" >
                <%= label_tag(:token, "token:") %>
                <%= text_field_tag(:token) %>
            </div>
            <div class="action" >
                <%= submit_tag("Borrar dentista") %>
            </div>
        <% end %>
    </div>





    <div class="card2">
        <h2> UPDATE Date (dentista) </h2>
        
        <%= form_with(url: api_updateDate_path, method: "get", remote: false, local:true) do %>
            <div class="field" >
                <%= label_tag(:token, "token:") %>
                <%= text_field_tag(:token) %>
            </div>
            <div class="field" >
                <%= label_tag(:dateId, "dateId:") %>
                <%= text_field_tag(:dateId) %>
            </div>
            <div class="field" >
                <%= label_tag(:state, "state:") %>
                <%= text_field_tag(:state) %>
            </div>
            <div class="action" >
                <%= submit_tag("Actualizar cita") %>
            </div>
        <% end %>
    </div>


    <div class="card2">
        <h2> UPDATE Dentist (dentista) </h2>
        
        <%= form_with(url: api_updateDentist_path, method: "get", remote: false, local:true) do %>
            <div class="field" >
                <%= label_tag(:token, "token:") %>
                <%= text_field_tag(:token) %>
            </div>
            <div class="field" >
                <%= label_tag(:name, "name:") %>
                <%= text_field_tag(:name) %>
            </div>
            <div class="field" >
                <%= label_tag(:year, "year:") %>
                <%= text_field_tag(:year) %>
            </div>
            <div class="field" >
                <%= label_tag(:phone, "phone:") %>
                <%= text_field_tag(:phone) %>
            </div>
            <div class="field" >
                <%= label_tag(:address, "address:") %>
                <%= text_field_tag(:address) %>
            </div>
            <div class="field" >
                <%= label_tag(:city, "city:") %>
                <%= text_field_tag(:city) %>
            </div>
            <div class="field" >
                <%= label_tag(:email, "email:") %>
                <%= text_field_tag(:email) %>
            </div>
            <div class="field" >
                <%= label_tag(:rut, "rut:") %>
                <%= text_field_tag(:rut) %>
            </div>
            <div class="field" >
                <%= label_tag(:voluntario, "voluntario:") %>
                <%= text_field_tag(:voluntario) %>
            </div>
            <div class="field" >
                <%= label_tag(:speciality, "speciality:") %>
                <%= text_field_tag(:speciality) %>
            </div>
            <div class="field" >
                <%= label_tag(:university, "university:") %>
                <%= text_field_tag(:university) %>
            </div>
            <div class="field" >
                <%= label_tag(:password, "password:") %>
                <%= text_field_tag(:password) %>
            </div>                                      
            <div class="action" >
                <%= submit_tag("Actualizar dentista") %>
            </div>
        <% end %>
    </div>


</div>

RubyApp/DentlistApp/app/views/welcome/resultado.html.erb
<header>
    <h1>DentList</h1>
    <p> Respuesta:</p>
</header>

<div class="topnav">
  <a href= <%=home_path%> > Inicio </a>

  <a id="r" <%= link_to "Volver", :back %>>  </a>
</div>

<div class="card">
    <h2>Current token: <%= @token %></h2>
    <h2>BODY</h2>
    <h5><%= @body %></h5>
</div>